// Generated by ts-to-zod
import { z } from "zod";

import { paramSchema } from "./parameter.internal.zod";
import { baseHookSchema, methodNameSchema } from "./baseHook.internal.zod";

export const javaOverloadSchema = z.object({
    params: z.array(paramSchema)
});

export const javaMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    overloads: z.array(javaOverloadSchema).optional()
});

export const javaMethodSchema = javaMethodDefinitionSchema;

export const javaHookSchema = baseHookSchema.extend({
    type: z.literal("java"),
    javaClass: z.string(),
    methods: z.array(javaMethodSchema)
});
