// Generated by ts-to-zod
import { z } from "zod";

import { paramSchema } from "./parameter.zod";
import { hookSchema, returnTypeSchema } from "./hook.zod";

export const symbolNameSchema = z.string();

export const symbolDefinitionSchema = z.object({
    symbol: symbolNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const nativeSymbolSchema = symbolDefinitionSchema;

export const nativeHookSchema = hookSchema.extend({
    type: z.literal("native"),
    module: z.string(),
    functions: z.array(nativeSymbolSchema)
});
