// Generated by ts-to-zod
import { z } from "zod";

import { nativeHookSchema, symbolDefinitionSchema, symbolNameSchema } from "./nativeHook.internal.zod";

const paramYamlParsingSchema = z.any();

export const symbolDefinitionInputSchema = symbolDefinitionSchema.omit({ "params": true }).extend({
    params: z.array(paramYamlParsingSchema).optional()
});

export const nativeSymbolSchema = z.union([symbolNameSchema, symbolDefinitionInputSchema]);

export const nativeHookYamlParsingSchema = nativeHookSchema.omit({ "functions": true }).extend({
    functions: z.array(nativeSymbolSchema)
});
