// Generated by ts-to-zod
import { z } from "zod";

import { paramSchema } from "./parameter.internal.zod";
import { baseHookSchema, methodNameSchema, returnTypeSchema } from "./baseHook.internal.zod";

export const objcMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const objcMethodSchema = objcMethodDefinitionSchema;

export const objcHookSchema = baseHookSchema.extend({
    type: z.literal("objc"),
    objcClass: z.string(),
    methods: z.array(objcMethodSchema)
});
