// Generated by ts-to-zod
import { z } from "zod";

import { objcHookSchema, objcMethodDefinitionSchema } from "./objcHook.zod";
import { methodNameSchema } from "./hook.zod";

export const objcMethodYamlParsingSchema = z.union([methodNameSchema, objcMethodDefinitionSchema]);

export const objcHookYamlParsingSchema = objcHookSchema.omit({ "methods": true }).extend({
    methods: z.array(objcMethodYamlParsingSchema)
});
