// Generated by ts-to-zod
import { z } from "zod";

import { paramSchema, paramNameSchema, paramOptionsSchema, paramTypeSchema } from "./parameter.zod";

export const paramYamlParsingSchema = z.union([paramSchema, paramTypeSchema, z.tuple([paramTypeSchema, paramNameSchema]), z.tuple([paramTypeSchema, paramOptionsSchema]), z.tuple([paramTypeSchema, paramNameSchema, paramOptionsSchema])]);
