// Generated by ts-to-zod
import { z } from "zod";

import { methodNameSchema, paramSchema } from "./../parameter.zod";
import { baseHookSchema } from "./baseHook.zod";

const returnTypeSchema = z.any();

export const nativeMethodDefinitionSchema = z.object({
    symbol: methodNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const nativeMethodSchema = z.union([methodNameSchema, nativeMethodDefinitionSchema]);

export const nativeHookSchema = baseHookSchema.extend({
    objcClass: z.string(),
    methods: z.array(nativeMethodSchema)
});
