// Generated by ts-to-zod
import { z } from "zod";

import { methodNameSchema, paramSchema } from "./../parameter.zod";
import { returnTypeSchema } from "./../returnType.zod";
import { baseHookSchema } from "./baseHook.zod";

export const objCMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const objCMethodSchema = z.union([methodNameSchema, objCMethodDefinitionSchema]);

export const objCHookSchema = baseHookSchema.extend({
    objcClass: z.string(),
    methods: z.array(objCMethodSchema)
});
