metadata:
  name: Test Settings Android
  description: |
    This frooky config uses different kind of settings:

      1. Global Settings

        Global settings can be of the type `HookSettings` and `DecoderSettings`. They apply to all hooks and their decoders (Parameter and Return Type), if they are not already set locally.

        Example: 

        ```
        globalSettings
          hookSettings:
            hookTimeout:     1
            stackTraceLimit: 10
            eventFilter: ['^(?!android).*']
          decoderSettings:
            fastDecode: true
            magicDecode: true 
            maxRecursion: 5
            decodeLimit: 100
        ``` 

      2. Hook and Decoder Settings 

        Hook and decoder settings define the behavior of the local hook. 

        Example: 
        
        ```
        <specific-hook>
          hookSettings:
            hookTimeout:     1
            stackTraceLimit: 10
            eventFilter: ['^(?!android).*']
          decoderSettings:
            fastDecode: true
            magicDecode: true 
            maxRecursion: 5
            decodeLimit: 100
        ```

      3. Parameter Settings

        Parameter settings (`ParamSettings`) define when a parameter is decoded (`decodeAt`), as well as the settings defined in `DecoderSettings`.

        Example: 
        
        ```
        decodeAt: exit
        fastDecode: true
        magicDecode: true 
        maxRecursion: 5
        decodeLimit: 100
        ```

      4. Return Type Settings

        Return type settings are `DecoderSettings` applied when the return value is decoded

        Example: 
        
        ```
        fastDecode: true
        magicDecode: true 
        maxRecursion: 5
        decodeLimit: 100
        ```
  version: 1
  author: frooky dev
  platform: Android

# global settings for the hooks in this hook file.
globalSettings:
  hookSettings:
    hookTimeout: 5                    # Timeout in seconds frooky will try to hook in case something the target library is not available.
    stackTraceLimit: 11               # Sets stackTraceLimit to 10 for all hooks
    eventFilter: ['^(?!android).*']   # Stack trace filters to apply.
  decoderSettings:
    fastDecode: true                  # If set, the decoders are instructed to prioritize speed over details. Mostly, this mean avoiding expensive Frida <-> native roundtrip.
    magicDecode: true                 # If set, frooky tries to guess the type of a value in case it is not declared in the hook, or it is not possible to deduct it at runtime
    maxRecursion: 1                   # Sets the cutoff limit for the recursion depth when decoding nested data structures, such as nested arrays, lists, sets, maps, structs etc.
    decodeLimit: 11                   # Sets the limit of how many elements of a enumerable data structures, such as arrays, lists, dictionaries etc. are decoded

hookGroup:
  # simple method declaration
  - javaClass: org.owasp.mastestapp.MastgTest
    hooks:
      - receiveBoolean

  # object with ONLY name provided, technically the same form as the one before
  - javaClass: org.owasp.mastestapp.MastgTest
    hooks:
      - method: receiveByte


  # PARTIAL local hook settings take priority over global setting, simple function declaration
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 2
    decoderSettings:
      decodeLimit: 22
    hooks:
      - receiveShort
      - receiveInt

  # PARTIAL local hook settings take priority over global setting, simple function declaration
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 3
    decoderSettings:
      decodeLimit: 33
    hooks:
      - method: receiveLong

  # PARTIAL local hook settings take priority over global setting, object with ONLY symbol provided
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 4
    decoderSettings:
      decodeLimit: 44
    hooks:
      - receiveFloat
      - receiveDouble


  # PARTIAL local parameter settings take priority over global setting, form [type, settings]
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 0
    hooks:
      - method: receiveIntArray
        overloads:
          - params:
            - ["[I", {decodeLimit: 55}]

  # PARTIAL local parameter settings take priority over global setting, form [type, name, settings]
  - javaClass: org.owasp.mastestapp.MastgTest
    hookSettings:
      stackTraceLimit: 4
    hooks:
      - method: receiveNestedPrimitivesArray
        overloads:
          - params:
            - ["[[[I", {decodeLimit: 66}]
