metadata:
  name: Test cases for testing global / hook / decoder settings
  version: 1
  author: frooky dev
  platform: Android

# global settings for the hooks in this hook file.
globalSettings:
  hookSettings:
    hookTimeout:     11   # Timeout in seconds frooky will try to hook in case something the target library is not available.
    stackTraceLimit: 11          # Sets stackTraceLimit to 10 for all hooks
    eventFilter: []              # Stack trace filters to apply.
  decoderSettings:
    fastDecode: true             # If set, the decoders are instructed to prioritize speed over details. Mostly, this mean avoiding expensive Frida <-> native roundtrip.
    magicDecode: true            # If set, frooky tries to guess the type of a value in case it is not declared in the hook, or it is not possible to deduct it at runtime
    maxRecursion: 11    # Sets the cutoff limit for the recursion depth when decoding nested data structures, such as nested arrays, lists, sets, maps, structs etc.
    decodeLimit: 11              # Sets the limit of how many elements of a enumerable data structures, such as arrays, lists, dictionaries etc. are decoded

hooks:
# decode argument: null terminated string 
  - module: libreceiveString.so
    hookSettings:
      stackTraceLimit: 55
    decoderSettings:
      decodeLimit: 55
    functions:
      - symbol: receive_cstring
        params:
          - char *
      #     - [char *, string]
      # - symbol: receive_utf8
      #   returnType: [ int, { decodeLimit: 777 } ]
      #   params:
      #     - [ char *, { decodeAt: enter, decodeLimit: 99 }]

  # - module: libreceiveFundamentalReference.so
  #   functions:
  #     - symbol: receive_bool_ref      # retType string
  #       retType: void
  #     - symbol: receive_char_ref      # retType string
  #       params:
  #         - [char*, minAsciiRef]
  #         - [char*, maxAsciiRef]
  #     - symbol: receive_schar_ref
  #       params:
  #         - [schar*, minScharRef]
  #         - [schar*, maxScharRef]