// Generated by ts-to-zod
import { z } from "zod";

import { decodeAtSchema } from "./param.zod";

export const decoderSettingsSchema = z.object({
    maxRecursion: z.number(),
    decodeLimit: z.number(),
    magicDecode: z.boolean(),
    fastDecode: z.boolean()
});

export const returnDecoderSettingsSchema = decoderSettingsSchema.extend({
    decoderArgs: z.array(z.string())
});

export const paramDecoderSettingsSchema = decoderSettingsSchema.extend({
    decoderArgs: z.array(z.string()),
    decodeAt: decodeAtSchema
});
