// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { paramSettingsSchema } from "./settingsInput.zod";

export const paramInputSchema = z.union([z.string(), z.tuple([z.string(), z.string()]), z.tuple([z.string(), paramSettingsSchema]), z.tuple([z.string(), z.string(), paramSettingsSchema])]);

export const retTypeInputSchema = z.union([z.string(), z.tuple([z.string(), decoderSettingsSchema.partial()])]);
