// Generated by ts-to-zod
import { z } from "zod";

export const decoderSettingsSchema = z.object({
    maxRecursion: z.number().optional(),
    decodeLimit: z.number().optional(),
    magicDecode: z.boolean().optional(),
    fastDecode: z.boolean().optional()
});
