// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";

export const platformSchema = z.union([z.literal("Android"), z.literal("iOS")]);

export const hookMetadataSchema = z.object({
    platform: platformSchema.optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    author: z.string().optional(),
    version: z.union([z.string(), z.number()]).optional()
});

const hookSettingsSchema = z.any();

const hookSchema = z.any();

export const frookyConfigSchema = z.object({
    metadata: hookMetadataSchema.optional(),
    globalSettings: z.object({
        hookSettings: hookSettingsSchema.optional(),
        decoderSettings: decoderSettingsSchema.optional()
    }).optional(),
    hooks: z.array(hookSchema)
});
