// Generated by ts-to-zod
import { z } from "zod";

import { hookMetadataSchema } from "./frookyConfig.zod";

export const returnTypeSchema = z.string();

export const methodNameSchema = z.string();

const decoderSettingsSchema = z.any();

export const hookSettingsSchema = z.object({
    stackTraceLimit: z.number().optional(),
    eventFilter: z.array(z.string()).optional(),
    decoderSettings: decoderSettingsSchema.optional()
});

export const hookSchema = z.object({
    metadata: hookMetadataSchema.optional(),
    settings: hookSettingsSchema.optional()
});
