// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";

export const hookSettingsSchema = z.object({
    stackTraceLimit: z.number(),
    eventFilter: z.array(z.string()),
    hookTimeout: z.number()
});

export const returnTypeSchema = z.string();

export const methodNameSchema = z.string();

export const hookSchema = z.object({
    hookSettings: hookSettingsSchema,
    decoderSettings: decoderSettingsSchema
});
