// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema, returnDecoderSettingsSchema } from "./decoderSettings.zod";
import { paramTypeSchema } from "./param.zod";

export const hookSettingsSchema = z.object({
    stackTraceLimit: z.number(),
    eventFilter: z.array(z.string()),
    hookTimeout: z.number()
});

export const methodNameSchema = z.string();

export const hookSchema = z.object({
    hookSettings: hookSettingsSchema,
    decoderSettings: decoderSettingsSchema
});

const baseDecoderSchema = z.any();

export const frookyReturnTypeSchema = z.object({
    type: paramTypeSchema,
    decoder: baseDecoderSchema.optional(),
    decoderSettings: returnDecoderSettingsSchema
});
