// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { hookSchema } from "./hook.zod";

const javaParamSchema = z.any();

const retTypeSchema = z.any();

export const javaOverloadSchema = z.object({
    params: z.array(javaParamSchema)
});

export const javaMethodSchema = z.object({
    name: z.string(),
    retType: retTypeSchema.optional(),
    overloads: z.array(javaOverloadSchema).optional(),
    decoderSettings: decoderSettingsSchema
});

export const javaHookSchema = hookSchema.extend({
    javaClass: z.string(),
    methods: z.array(javaMethodSchema)
});
