// Generated by ts-to-zod
import { z } from "zod";

import { frookyReturnTypeSchema, hookSchema, methodNameSchema } from "./hook.zod";
import { paramSchema } from "./param.zod";

export const javaOverloadSchema = z.object({
    params: z.array(paramSchema)
});

export const javaMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    returnType: frookyReturnTypeSchema.optional(),
    overloads: z.array(javaOverloadSchema).optional()
});

export const javaMethodSchema = javaMethodDefinitionSchema;

export const javaHookSchema = hookSchema.extend({
    javaClass: z.string(),
    methods: z.array(javaMethodSchema)
});
