// Generated by ts-to-zod
import { z } from "zod";

import { hookSchema, methodNameSchema } from "./hook.zod";

const javaParamSchema = z.any();

const retTypeSchema = z.any();

export const javaOverloadSchema = z.object({
    params: z.array(javaParamSchema)
});

export const javaMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    returnType: retTypeSchema.optional(),
    overloads: z.array(javaOverloadSchema).optional()
});

export const javaMethodSchema = javaMethodDefinitionSchema;

export const javaHookSchema = hookSchema.extend({
    javaClass: z.string(),
    methods: z.array(javaMethodSchema)
});
