// Generated by ts-to-zod
import { z } from "zod";

import { javaHookSchema, javaMethodDefinitionSchema, javaOverloadSchema } from "./javaHook.zod";
import { methodNameSchema } from "./hook.zod";
import { paramInputSchema } from "./param.input.zod";

export const javaOverloadInputSchema = javaOverloadSchema.omit({ "params": true }).extend({
    params: z.array(paramInputSchema)
});

export const javaMethodDefinitionInputSchema = javaMethodDefinitionSchema.omit({ "overloads": true }).extend({
    overloads: z.array(javaOverloadInputSchema).optional()
});

export const javaMethodInputSchema = z.union([methodNameSchema, javaMethodDefinitionInputSchema]);

export const javaHookInputSchema = javaHookSchema.omit({ "methods": true }).extend({
    type: z.literal("java"),
    methods: z.array(javaMethodInputSchema)
});
