// Generated by ts-to-zod
import { z } from "zod";

import { javaHookSchema, javaMethodSchema, javaOverloadSchema } from "./javaHook.zod";
import { decoderSettingsSchema } from "./decoderSettings.zod";
import { paramInputSchema, retTypeInputSchema } from "./decodableTypesInput.zod";
import { decoderSettingsInputSchema, hookSettingsInputSchema } from "./settingsInput.zod";

export const javaOverloadInputSchema = javaOverloadSchema.omit({ "params": true }).extend({
    params: z.array(paramInputSchema)
});

export const javaMethodInputSchema = z.union([z.string(), javaMethodSchema.omit({ "overloads": true, "retType": true, "decoderSettings": true }).and(z.object({
        overloads: z.array(javaOverloadInputSchema).optional(),
        retType: retTypeInputSchema.optional(),
        decoderSettings: decoderSettingsSchema.optional()
    }))]);

export const javaHookInputSchema = javaHookSchema.omit({ "methods": true, "hookSettings": true, "decoderSettings": true }).extend({
    type: z.literal("java"),
    methods: z.array(javaMethodInputSchema),
    hookSettings: hookSettingsInputSchema.optional(),
    decoderSettings: decoderSettingsInputSchema.optional()
});
