// Generated by ts-to-zod
import { z } from "zod";

import { hookSchema } from "./hook.zod";

export const symbolNameSchema = z.string();

const paramSchema = z.any();

export const nativeFrookyFunctionDefinitionSchema = z.object({
    symbol: symbolNameSchema,
    returnType: paramSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const nativeFrookyFunctionSchema = nativeFrookyFunctionDefinitionSchema;

export const nativeHookSchema = hookSchema.extend({
    module: z.string(),
    functions: z.array(nativeFrookyFunctionSchema)
});
