// Generated by ts-to-zod
import { z } from "zod";

import { hookSchema } from "./hook.zod";

const retTypeSchema = z.any();

const nativeParamSchema = z.any();

export const nativeFrookyFunctionSchema = z.object({
    symbol: z.string(),
    returnType: retTypeSchema.optional(),
    params: z.array(nativeParamSchema).optional()
});

export const nativeHookSchema = hookSchema.extend({
    module: z.string(),
    functions: z.array(nativeFrookyFunctionSchema)
});
