// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { hookSchema } from "./hook.zod";

const nativeParamSchema = z.any();

const retTypeSchema = z.any();

export const nativeFrookyFunctionSchema = z.object({
    symbol: z.string(),
    params: z.array(nativeParamSchema).optional(),
    retType: retTypeSchema.optional(),
    decoderSettings: decoderSettingsSchema
});

export const nativeHookSchema = hookSchema.extend({
    module: z.string(),
    functions: z.array(nativeFrookyFunctionSchema)
});
