// Generated by ts-to-zod
import { z } from "zod";

import { nativeFrookyFunctionSchema, nativeHookSchema } from "./nativeHook.internal.zod";
import { paramInputSchema, returnTypeInputSchema } from "./decodableTypesInput.zod";
import { decoderSettingsInputSchema, hookSettingsInputSchema } from "./settingsInput.zod";

export const nativeFrookyFunctionInputSchema = nativeFrookyFunctionSchema.omit({ "params": true, "returnType": true }).extend({
    params: z.array(paramInputSchema).optional(),
    returnType: returnTypeInputSchema.optional()
});

export const nativeHookInputSchema = nativeHookSchema.omit({ "functions": true, "hookSettings": true, "decoderSettings": true }).extend({
    type: z.literal("native"),
    functions: z.array(nativeFrookyFunctionInputSchema),
    hookSettings: hookSettingsInputSchema.optional(),
    decoderSettings: decoderSettingsInputSchema.optional()
});
