// Generated by ts-to-zod
import { z } from "zod";

import { nativeFrookyFunctionDefinitionSchema, nativeHookSchema, symbolNameSchema } from "./nativeHook.internal.zod";
import { paramInputSchema } from "./param.input.zod";

export const nativeFunctionDefinitionInputSchema = nativeFrookyFunctionDefinitionSchema.omit({ "params": true }).extend({
    params: z.array(paramInputSchema).optional()
});

export const nativeFrookyFunctionSchema = z.union([symbolNameSchema, nativeFunctionDefinitionInputSchema]);

export const nativeHookInputSchema = nativeHookSchema.omit({ "functions": true }).extend({
    type: z.literal("native"),
    functions: z.array(nativeFrookyFunctionSchema)
});
