// Generated by ts-to-zod
import { z } from "zod";

import { objcHookSchema } from "./objcHook.zod";
import { paramInputSchema, returnTypeInputSchema } from "./decodableTypesInput.zod";
import { decoderSettingsInputSchema, hookSettingsInputSchema } from "./settingsInput.zod";

export const objcMethodDefinitionInputSchema = z.object({
    name: z.string(),
    returnType: returnTypeInputSchema.optional(),
    params: z.array(paramInputSchema).optional()
});

export const objcMethodInputSchema = z.union([z.string(), objcMethodDefinitionInputSchema]);

export const objcHookInputSchema = objcHookSchema.omit({ "methods": true, "hookSettings": true, "decoderSettings": true }).extend({
    type: z.literal("objc"),
    methods: z.array(objcMethodInputSchema),
    hookSettings: hookSettingsInputSchema.optional(),
    decoderSettings: decoderSettingsInputSchema.optional()
});
