// Generated by ts-to-zod
import { z } from "zod";

import { hookSchema } from "./hook.zod";

const retTypeSchema = z.any();

const paramSchema = z.any();

export const objcMethodSchema = z.object({
    name: z.string(),
    returnType: retTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const objcHookSchema = hookSchema.extend({
    objcClass: z.string(),
    methods: z.array(objcMethodSchema)
});
