// Generated by ts-to-zod
import { z } from "zod";

import { hookSchema, methodNameSchema } from "./hook.zod";

const retTypeSchema = z.any();

const paramSchema = z.any();

export const objcMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    returnType: retTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const objcMethodSchema = objcMethodDefinitionSchema;

export const objcHookSchema = hookSchema.extend({
    objcClass: z.string(),
    methods: z.array(objcMethodSchema)
});
