// Generated by ts-to-zod
import { z } from "zod";

import { objcHookSchema, objcMethodSchema } from "./objcHook.zod";
import { decoderSettingsInputSchema, hookSettingsInputSchema } from "./settingsInput.zod";

export const objcMethodInputSchema = z.union([z.string(), objcMethodSchema]);

export const objcHookInputSchema = objcHookSchema.omit({ "methods": true, "hookSettings": true, "decoderSettings": true }).extend({
    type: z.literal("objc"),
    methods: z.array(objcMethodInputSchema),
    hookSettings: hookSettingsInputSchema.optional(),
    decoderSettings: decoderSettingsInputSchema.optional()
});
