// Generated by ts-to-zod
import { z } from "zod";

import { paramSchema, paramNameSchema, paramOptionsSchema, paramTypeSchema } from "./param.zod";

export const paramInputSchema = z.union([paramTypeSchema, z.tuple([paramTypeSchema, paramOptionsSchema]), z.tuple([paramTypeSchema, paramNameSchema]), z.tuple([paramTypeSchema, paramNameSchema, paramOptionsSchema]), paramSchema]);
