// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";

export const decodeAtSchema = z.union([z.literal("enter"), z.literal("exit"), z.literal("both")]);

export const paramTypeSchema = z.string();

export const paramNameSchema = z.string();

export const paramOptionsSchema = z.object({
    decodeAt: decodeAtSchema.optional(),
    decoderArgs: z.array(z.string()).optional(),
    decoderSettings: decoderSettingsSchema
});

const baseDecoderSchema = z.any();

export const paramSchema = z.object({
    type: paramTypeSchema,
    name: paramNameSchema.optional(),
    decoder: baseDecoderSchema.optional(),
    decoderSettings: decoderSettingsSchema
});
