// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { paramSchema, paramNameSchema, paramTypeSchema } from "./param.zod";

export const paramInputSchema = z.union([paramTypeSchema, z.tuple([paramTypeSchema, decoderSettingsSchema.partial()]), z.tuple([paramTypeSchema, paramNameSchema]), z.tuple([paramTypeSchema, paramNameSchema, decoderSettingsSchema.partial()]), paramSchema]);
