// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { hookSettingsSchema } from "./hook.zod";

export const hookSettingsInputSchema = hookSettingsSchema.partial();

export const decoderSettingsInputSchema = decoderSettingsSchema.partial();
