// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema, paramDecoderSettingsSchema, returnDecoderSettingsSchema } from "./decoderSettings.zod";
import { hookSettingsSchema } from "./hook.zod";

export const hookSettingsInputSchema = hookSettingsSchema.partial();

export const decoderSettingsInputSchema = decoderSettingsSchema.partial();

export const returnDecoderSettingsInputSchema = returnDecoderSettingsSchema.partial();

export const paramDecoderSettingsInputSchema = paramDecoderSettingsSchema.partial();
