name: Setup Frida
description: Setup Python & install Frida
runs:
  using: composite
  steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Frida
        shell: bash
        run: |
          python -m pip install frida
          python -m pip install frida-tools
