// Generated by ts-to-zod
import { z } from "zod";

import { javaHookSchema, javaMethodDefinitionSchema } from "./javaHook.internal.zod";
import { methodNameSchema } from "./baseHook.internal.zod";

export const javaMethodSchema = z.union([methodNameSchema, javaMethodDefinitionSchema]);

export const javaHookInputSchema = javaHookSchema.omit({ "methods": true }).extend({
    methods: z.array(javaMethodSchema)
});
