// Generated by ts-to-zod
import { z } from "zod";

import { objcHookSchema, objcMethodDefinitionSchema } from "./objcHook..internal.zod";
import { methodNameSchema } from "./baseHook.internal.zod";

export const objcMethodSchema = z.union([methodNameSchema, objcMethodDefinitionSchema]);

export const objcHookInputSchema = objcHookSchema.omit({ "methods": true }).extend({
    methods: z.array(objcMethodSchema)
});
