// Generated by ts-to-zod
import { z } from "zod";

export const hookSettingsSchema = z.object({
    stackTraceLimit: z.number(),
    eventFilter: z.array(z.string())
});

export const decoderSettingsSchema = z.object({
    maxRecursion: z.number(),
    decodeLimit: z.number(),
    magicDecode: z.boolean(),
    fastDecode: z.boolean(),
    customDecoder: z.string(),
    decoderArgs: z.array(z.string())
});

export const frookySettingsSchema = z.object({
    hookSettings: hookSettingsSchema,
    decoderSettings: decoderSettingsSchema
});
