// Generated by ts-to-zod
import { z } from "zod";

import { logLevelSchema, logToSchema } from "./logger.zod";

export const hookSettingsSchema = z.object({
    stackTraceLimit: z.number(),
    eventFilter: z.array(z.string())
});

export const decoderSettingsSchema = z.object({
    maxRecursion: z.number(),
    decodeLimit: z.number(),
    magicDecode: z.boolean(),
    fastDecode: z.boolean(),
    customDecoder: z.string(),
    decoderArgs: z.array(z.string())
});

export const frookySettingsSchema = z.object({
    verbose: z.union([z.literal(true), z.literal(false)]),
    logLevel: logLevelSchema,
    logTo: logToSchema,
    resolverTimeout: z.number(),
    hookSettings: hookSettingsSchema,
    decoderSettings: decoderSettingsSchema
});
