// Generated by ts-to-zod
import { z } from "zod";

import { frookyMetadataSchema } from "./frookyMetadata.zod";
import { inputJavaHookGroupSchema } from "./inputJavaHookGroup.zod";
import { inputNativeHookGroupSchema } from "./inputNativeHookGroup.zod";
import { inputFrookySettingsSchema } from "./inputSettings.zod";

export const frookyConfigSchema = z.object({
    metadata: frookyMetadataSchema.optional(),
    settings: inputFrookySettingsSchema.optional(),
    hookGroup: z.union([z.array(inputJavaHookGroupSchema), z.array(inputNativeHookGroupSchema)])
});
