// Generated by ts-to-zod
import { z } from "zod";

export const hookSettingsSchema = z.object({
    stackTraceLimit: z.number(),
    stackTraceFilter: z.array(z.string())
});

export const decoderSettingsSchema = z.object({
    maxRecursion: z.number(),
    decodeLimit: z.number(),
    magicDecode: z.boolean(),
    fastDecode: z.boolean(),
    customDecoder: z.string().optional(),
    decoderArg: z.string().optional(),
    paramFilter: z.array(z.string()).optional()
});

export const frookySettingsSchema = z.object({
    hookSettings: hookSettingsSchema,
    decoderSettings: decoderSettingsSchema
});
