// Generated by ts-to-zod
import { z } from "zod";

export const platformSchema = z.union([z.literal("Android"), z.literal("iOS")]);

export const frookyMetadataSchema = z.object({
    platform: platformSchema.optional(),
    name: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    author: z.string().optional(),
    version: z.union([z.string(), z.number()]).optional()
});
