// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema, hookSettingsSchema } from "./frookySettings.zod";
import { inputParamSchema, inputRetTypeSchema } from "./inputDecodableTypes.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./inputSettings.zod";

export const inputOverloadSchema = z.object({
    params: z.array(inputParamSchema)
});

export const inputJavaHookNormalizedSchema = z.object({
    javaClass: z.string(),
    method: z.string(),
    overloads: z.array(inputOverloadSchema).optional(),
    retType: inputRetTypeSchema.optional(),
    hookSettings: hookSettingsSchema.optional(),
    decoderSettings: decoderSettingsSchema.optional()
});

export const inputJavaHookSchema = z.union([z.string(), inputJavaHookNormalizedSchema]);

export const inputJavaHookGroupSchema = z.object({
    type: z.literal("java"),
    javaClass: z.string(),
    hooks: z.array(inputJavaHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
