// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { hookSettingsSchema } from "./hookSettings.zod";

export const inputHookSettingsSchema = hookSettingsSchema.partial();

export const inputDecoderSettingsSchema = decoderSettingsSchema.partial();

const decodeAtSchema = z.any();

export const inputParamSettingsSchema = decoderSettingsSchema.partial().and(z.object({
    decodeAt: decodeAtSchema.optional()
}));
