// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema, frookySettingsSchema, hookSettingsSchema } from "./frookySettings.zod";

export const inputHookSettingsSchema = hookSettingsSchema.partial();

export const inputDecoderSettingsSchema = decoderSettingsSchema.partial();

const decodeAtSchema = z.any();

export const inputFrookySettingsSchema = frookySettingsSchema.partial().omit({ "hookSettings": true, "decoderSettings": true }).and(z.object({
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
}));

export const inputParamSettingsSchema = decoderSettingsSchema.partial().and(z.object({
    decodeAt: decodeAtSchema.optional()
}));
