// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { inputParamSettingsSchema } from "./inputSettings.zod";

const paramSchema = z.any();

const decodableTypeSchema = z.any();

export const inputParamSchema = z.union([z.string(), z.tuple([z.string(), z.string()]), z.tuple([z.string(), inputParamSettingsSchema]), z.tuple([z.string(), z.string(), inputParamSettingsSchema]), paramSchema]);

export const inputRetTypeSchema = z.union([z.string(), z.tuple([z.string(), decoderSettingsSchema.partial()]), decodableTypeSchema]);
