// Generated by ts-to-zod
import { z } from "zod";

import { javaHookSchema, javaMethodDefinitionSchema, javaOverloadSchema } from "./javaHook.zod";
import { methodNameSchema } from "./hook.zod";
import { paramYamlInputSchema } from "./parameter.input.zod";

export const javaOverloadYamlParsingSchema = javaOverloadSchema.omit({ "params": true }).extend({
    params: z.array(paramYamlInputSchema)
});

export const javaMethodDefinitionInputSchema = javaMethodDefinitionSchema.omit({ "overloads": true }).extend({
    overloads: z.array(javaOverloadYamlParsingSchema).optional()
});

export const javaMethodSchema = z.union([methodNameSchema, javaMethodDefinitionInputSchema]);

export const javaHookInputSchema = javaHookSchema.omit({ "methods": true }).extend({
    methods: z.array(javaMethodSchema)
});
