// Generated by ts-to-zod
import { z } from "zod";
import { methodNameSchema } from "./hook.zod";
import {
	javaHookSchema,
	javaMethodDefinitionSchema,
	javaOverloadSchema,
} from "./javaHook.zod";
import { paramInputSchema } from "./parameter.input.zod";

export const javaOverloadInputSchema = javaOverloadSchema
	.omit({ params: true })
	.extend({
		params: z.array(paramInputSchema),
	});

export const javaMethodDefinitionInputSchema = javaMethodDefinitionSchema
	.omit({ overloads: true })
	.extend({
		overloads: z.array(javaOverloadInputSchema).optional(),
	});

export const javaMethodSchema = z.union([
	methodNameSchema,
	javaMethodDefinitionInputSchema,
]);

export const javaHookInputSchema = javaHookSchema
	.omit({ methods: true })
	.extend({
		methods: z.array(javaMethodSchema),
	});
