// Generated by ts-to-zod
import { z } from "zod";

export const logLevelSchema = z.union([z.literal("none"), z.literal("error"), z.literal("warn"), z.literal("info"), z.literal("debug")]);

export const logToSchema = z.union([z.literal("console"), z.literal("log")]);
