// Generated by ts-to-zod
import { z } from "zod";

export const logLevelSchema = z.union([z.literal("info"), z.literal("warn"), z.literal("error"), z.literal("debug")]);

export const logToSchema = z.union([z.literal("device"), z.literal("frooky")]);
