// Generated by ts-to-zod
import { z } from "zod";

import { nativeHookSchema, symbolDefinitionSchema, symbolNameSchema } from "./nativeHook.internal.zod";
import { paramYamlInputSchema } from "./parameter.yaml.parsing.zod";

export const symbolDefinitionInputSchema = symbolDefinitionSchema.omit({ "params": true }).extend({
    params: z.array(paramYamlInputSchema).optional()
});

export const nativeSymbolSchema = z.union([symbolNameSchema, symbolDefinitionInputSchema]);

export const nativeHookInputSchema = nativeHookSchema.omit({ "functions": true }).extend({
    functions: z.array(nativeSymbolSchema)
});
