// Generated by ts-to-zod
import { z } from "zod";

import { hookSchema, returnTypeSchema } from "./hook.zod";

export const symbolNameSchema = z.string();

const paramSchema = z.any();

export const nativeFunctionDefinitionSchema = z.object({
    symbol: symbolNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const nativeFunctionSchema = nativeFunctionDefinitionSchema;

export const nativeHookSchema = hookSchema.extend({
    module: z.string(),
    functions: z.array(nativeFunctionSchema)
});
