// Generated by ts-to-zod
import { z } from "zod";

import { nativeHookSchema, symbolDefinitionSchema, symbolNameSchema } from "./nativeHook.internal.zod";
import { paramInputSchema } from "./parameter.input.zod";

export const symbolDefinitionInputSchema = symbolDefinitionSchema.omit({ "params": true }).extend({
    params: z.array(paramInputSchema).optional()
});

export const nativeSymbolSchema = z.union([symbolNameSchema, symbolDefinitionInputSchema]);

export const nativeHookInputSchema = nativeHookSchema.omit({ "functions": true }).extend({
    type: z.literal("native"),
    functions: z.array(nativeSymbolSchema)
});
