// Generated by ts-to-zod
import { z } from "zod";

import { objcHookSchema, objcMethodDefinitionSchema } from "./objcHook.zod";
import { methodNameSchema } from "./hook.zod";

export const objcMethodInputSchema = z.union([methodNameSchema, objcMethodDefinitionSchema]);

export const objcHookInputSchema = objcHookSchema.omit({ "methods": true }).extend({
    methods: z.array(objcMethodInputSchema)
});
