// Generated by ts-to-zod
import { z } from "zod";

import { hookSchema, methodNameSchema, returnTypeSchema } from "./hook.zod";
import { paramSchema } from "./parameter.zod";

export const objcMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const objcMethodSchema = objcMethodDefinitionSchema;

export const objcHookSchema = hookSchema.extend({
    objcClass: z.string(),
    methods: z.array(objcMethodSchema)
});
