// Generated by ts-to-zod
import { z } from "zod";

import { objcHookSchema } from "./objcHook.zod";
import { methodNameSchema, returnTypeSchema } from "./hook.zod";
import { paramInputSchema } from "./parameter.input.zod";

export const objcMethodDefinitionInputSchema = z.object({
    name: methodNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramInputSchema).optional()
});

export const objcMethodInputSchema = z.union([methodNameSchema, objcMethodDefinitionInputSchema]);

export const objcHookInputSchema = objcHookSchema.omit({ "methods": true }).extend({
    type: z.literal("objc"),
    methods: z.array(objcMethodInputSchema)
});
