// Generated by ts-to-zod
import { z } from "zod";

import { paramDefinitionSchema, paramNameSchema, paramOptionsSchema, paramTypeSchema } from "./parameter.zod";

export const paramInputSchema = z.union([paramTypeSchema, paramDefinitionSchema, z.tuple([paramTypeSchema, paramNameSchema]), z.tuple([paramTypeSchema, paramOptionsSchema]), z.tuple([paramTypeSchema, paramNameSchema, paramOptionsSchema])]);
