// Generated by ts-to-zod
import { z } from "zod";

export const decoderSettingsSchema = z.object({
    maxRecursion: z.number(),
    decodeLimit: z.number(),
    magicDecode: z.boolean(),
    fastDecode: z.boolean()
});
