// Generated by ts-to-zod
import { z } from "zod";

export const hookSettingsSchema = z.object({
    stackTraceLimit: z.number(),
    eventFilter: z.array(z.string()),
    hookTimeoutMs: z.number()
});
