// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { hookSettingsSchema } from "./hookSettings.zod";
import { paramInputSchema, retTypeInputSchema } from "./decodableTypesInput.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./settingsInput.zod";

export const inputOverloadSchema = z.object({
    params: z.array(paramInputSchema)
});

export const inputJavaHookCanonicalSchema = z.object({
    className: z.string(),
    methodName: z.string(),
    overloads: z.array(inputOverloadSchema).optional(),
    retType: retTypeInputSchema.optional(),
    hookSettings: hookSettingsSchema.optional(),
    decoderSettings: decoderSettingsSchema.optional()
});

export const inputJavaHookSchema = z.union([z.string(), inputJavaHookCanonicalSchema]);

export const javaHookScopeSchema = z.object({
    type: z.literal("java"),
    javaClass: z.string(),
    hooks: z.array(inputJavaHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
