// Generated by ts-to-zod
import { z } from "zod";

import { decoderSettingsSchema } from "./decoderSettings.zod";
import { hookSettingsSchema } from "./hookSettings.zod";
import { paramInputSchema, retTypeInputSchema } from "./decodableTypesInput.zod";
import { inputDecoderSettingsSchema, inputHookSettingsSchema } from "./settingsInput.zod";

export const inputNativeHookCanonicalSchema = z.object({
    moduleName: z.string(),
    symbolName: z.string(),
    params: z.array(paramInputSchema).optional(),
    retType: retTypeInputSchema.optional(),
    hookSettings: hookSettingsSchema.optional(),
    decoderSettings: decoderSettingsSchema.optional()
});

export const inputNativeHookSchema = z.union([z.string(), inputNativeHookCanonicalSchema]);

export const nativeHookScopeSchema = z.object({
    type: z.literal("native"),
    module: z.string(),
    hooks: z.array(inputNativeHookSchema),
    hookSettings: inputHookSettingsSchema.optional(),
    decoderSettings: inputDecoderSettingsSchema.optional()
});
