// Generated by ts-to-zod
import { z } from "zod";

import { javaHookSchema } from "./hook/javaHook.zod";
import { nativeHookSchema } from "./hook/nativeHook.zod";
import { objCHookSchema } from "./hook/objcHook.zod";

export const platformSchema = z.union([z.literal("Android"), z.literal("iOS")]);

export const hookMetadataSchema = z.object({
    platform: platformSchema,
    name: z.string().optional(),
    description: z.string().optional(),
    category: z.string().optional(),
    author: z.string().optional(),
    version: z.string().optional()
});

export const hookSchema = z.union([javaHookSchema, nativeHookSchema, objCHookSchema]);

export const frookyConfigSchema = z.object({
    metadata: hookMetadataSchema.optional(),
    hooks: z.array(hookSchema)
});
