// Generated by ts-to-zod
import { z } from "zod";

export const decodeAtSchema = z.union([z.literal("enter"), z.literal("exit"), z.literal("both")]);

export const paramTypeSchema = z.string();

export const paramNameSchema = z.string();

export const paramOptionsSchema = z.object({
    decodeAt: decodeAtSchema.optional(),
    decoderArgs: z.array(z.string()).optional()
});

export const paramSchema = z.union([paramTypeSchema, z.tuple([paramTypeSchema, paramOptionsSchema]), z.tuple([paramTypeSchema, paramNameSchema, paramOptionsSchema]), z.object({
        type: paramTypeSchema,
        name: paramNameSchema.optional(),
        options: paramOptionsSchema.optional()
    })]);

export const methodNameSchema = z.string();
