// Generated by ts-to-zod
import { z } from "zod";

export const methodNameSchema = z.string();

export const baseHookSchema = z.object({
    stackTraceLimit: z.number().optional(),
    eventFilter: z.array(z.string()).optional()
});
