// Generated by ts-to-zod
import { z } from "zod";

import { paramSchema } from "./../parameter.zod";
import { baseHookSchema, methodNameSchema } from "./baseHook.zod";

export const javaOverloadSchema = z.object({
    params: z.array(paramSchema)
});

export const javaMethodDefinitionSchema = z.object({
    name: methodNameSchema,
    overloads: z.array(javaOverloadSchema).optional()
});

export const javaMethodSchema = z.union([methodNameSchema, javaMethodDefinitionSchema]);

export const javaHookSchema = baseHookSchema.extend({
    javaClass: z.string(),
    methods: z.array(javaMethodSchema)
});
