// Generated by ts-to-zod
import { z } from "zod";

import { paramSchema } from "./../parameter.zod";
import { baseHookSchema } from "./baseHook.zod";

export const symbolNameSchema = z.string();

const returnTypeSchema = z.any();

export const symbolDefinitionSchema = z.object({
    symbol: symbolNameSchema,
    returnType: returnTypeSchema.optional(),
    params: z.array(paramSchema).optional()
});

export const nativeSymbolSchema = z.union([symbolNameSchema, symbolDefinitionSchema]);

export const nativeHookSchema = baseHookSchema.extend({
    module: z.string(),
    symbol: z.array(nativeSymbolSchema)
});
