name: Build MAS app Android

on:
  push:
    paths:
      - 'test-apps/mas-app-android/**'
  workflow_call:

permissions:
  contents: read

jobs:
  build-mas-app-android:
    name: Build MAS app Android
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - uses: gradle/actions/setup-gradle@v6

      - working-directory: test-apps/mas-app-android
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v6
        with:
          name: mas-app-android
          path: test-apps/mas-app-android/app/build/outputs/apk/debug/app-debug.apk