name: Build frooky Host

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-frooky-agent:
    uses: ./.github/workflows/build-frooky-agent.yml

  build-frooky-host:
    name: Build frooky host
    needs: build-frooky-agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v6
        with:
          name: frooky-agent
          path: frooky/agent/dist
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - run: python -m pip install --upgrade build
      - run: python -m build
      - uses: actions/upload-artifact@v6
        with:
          name: frooky-host
          path: dist/*
