name: Build frooky Agent

on:
  push:
    paths:
      - 'frooky/agent/**'
  workflow_call:
    outputs:
      artifact-name:
        description: "frooky agent (JavaScript)"
        value: ${{ jobs.build-frooky-agent.outputs.artifact-name }}

permissions:
  contents: read

jobs:
  build-frooky-agent:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: 'npm'
          cache-dependency-path: './frooky/agent/package-lock.json'
      - working-directory: frooky/agent
        run: npm ci
      - working-directory: frooky/agent
        run: |
          npm run build:prod:android
          npm run build:prod:ios
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: agent-dist
          path: frooky/agent/dist/*