name: Build frooky Host

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-agent:
    uses: ./.github/workflows/build-agent.yml

  build-python:
    needs: build-agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v5
        with:
          name: frooky-agent
          path: frooky/agent/dist
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python -m pip install --upgrade build
      - run: python -m build
      - uses: actions/upload-artifact@v5
        with:
          name: dist
          path: dist/*
