name: Publish Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  build-frooky-host:
    permissions:
      contents: read
    uses: ./.github/workflows/build-frooky-host.yml

  verify-build:
    needs: [build]
    permissions:
      contents: read
    uses: ./.github/workflows/test-build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build-frooky-host
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: frooky-host
          path: dist/*
      - uses: pypa/gh-action-pypi-publish@release/v1