name: Temp workflow to trigger workflows during dev

on: [push]

jobs:
  test-android:
    uses: ./.github/workflows/test-frooky-agent-android.yml

  test-ios:
    uses: ./.github/workflows/test-frooky-agent-ios.yml