name: Temp workflow to trigger workflows during dev

on: [push]

jobs:
  build-frooky-agent:
    uses: ./.github/workflows/build-frooky-agent.yml

  test-ios:
    needs: build-frooky-agent
    uses: ./.github/workflows/test-frooky-agent-ios.yml

  # test-android:
  #   needs: build-frooky-agent
  #   uses: ./.github/workflows/test-frooky-agent-android.yml
