name: Test agent Android

on:
  push:
    # paths:
    #   - 'frooky/agent/**'

permissions:
  contents: read

jobs:
  build-app-android:
    uses: ./.github/workflows/build-app-android.yml

  test-agent-android:
    name: Test agent Android
    runs-on: ubuntu-latest
    needs: build-app-android
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download MAS app Android artifact
        uses: actions/download-artifact@v8
        with:
          name: target-apps-android
          path: target-apps-android

      - name: Setup Agent Test Environment
        uses: ./.github/actions/setup-agent-test-env

      - name: Setup Android emulator environment
        uses: ./.github/actions/setup-android-emulator
        with:
          api-level: "34"

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            echo "Starting adb as root"
            .github/scripts/android/prep-device.sh

            echo "Installing frida server"
            .github/scripts/android/install-frida-server.sh

            echo "Installing target apps"
            .github/scripts/android/install-target-apps.sh

            echo "Launching all target apps"
            .github/scripts/android/launch-target-apps.sh

            echo "Running Android agent tests"
            npm --prefix frooky/agent run test:android -- -i basic_parameter.frooky.target.app -o test-results.txt

      - name: Summarize test result
        if: always()
        run: |
          cat test-results.txt >> "$GITHUB_STEP_SUMMARY"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: test-results.txt
