name: Test frooky agent iOS

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-mas-app-iOS:
    uses: ./.github/workflows/build-mas-app-ios.yml

  test-frooky-agent-android:
    name: Test frooky agent iOS
    runs-on: ubuntu-latest
    needs: 
      - build-mas-app-iOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download frooky agent artifact
        uses: actions/download-artifact@v8
        with:
          name: frooky-agent
          path: frooky/agent/dist

      - name: Download MAS app iOS artifact
        uses: actions/download-artifact@v8
        with:
          name: mas-app-iOS
          path: mas-app-iOS
